# Generated by Django 4.0.4 on 2022-08-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='description_en',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='description_ru',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='description_uz',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
