# Generated by Django 4.0.4 on 2022-08-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_indexpagemodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='facebook',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='telegram',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='youtube',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
