# Generated by Django 4.0.4 on 2022-09-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_indexpagemodel_facebook_indexpagemodel_telegram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='phone',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
