# Generated by Django 4.0.4 on 2022-09-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_indexpagemodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='address_en',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='address_ru',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='address_uz',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
