# Generated by Django 4.0.4 on 2022-09-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_indexpagemodel_address_en_indexpagemodel_address_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='worktime_en',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='worktime_ru',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='worktime_uz',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
