# Generated by Django 4.0.4 on 2022-09-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_indexpageslidemodel_alter_indexpagemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpageslidemodel',
            name='link',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
    ]
