# Generated by Django 4.0.4 on 2022-09-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_indexpageslidemodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpageslidemodel',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
