# Generated by Django 4.0.4 on 2022-09-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_indexpageslidemodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_description_en',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_description_ru',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_description_uz',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_1_en',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_1_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_1_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_2_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_2_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_2_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_3_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_3_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_3_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_4_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_4_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_4_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_5_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_5_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_5_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_6_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_6_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_feature_6_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_img',
            field=models.ImageField(default=1, upload_to='indexpage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_subtitle_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_subtitle_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_subtitle_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_title_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_title_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_title_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
