# Generated by Django 4.0.4 on 2022-09-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_indexpagemodel_secondblock_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='secondblock_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
