# Generated by Django 4.0.4 on 2022-09-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_indexpagemodel_thirdblock_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='indexpage_products/')),
                ('title_ru', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField()),
            ],
            options={
                'verbose_name': 'Продукт для главной страницы',
                'verbose_name_plural': 'Продукты для главной страницы',
            },
        ),
    ]
