# Generated by Django 4.0.4 on 2022-09-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_indexpageproductmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexpageproductmodel',
            options={'verbose_name': 'Продукт главной страницы', 'verbose_name_plural': 'Продукты главной страницы'},
        ),
    ]
