# Generated by Django 4.0.4 on 2022-09-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_indexpageproductmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpageproductmodel',
            name='link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
