# Generated by Django 4.0.4 on 2022-09-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_indexpageproductmodel_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagemodel',
            name='fourthblock_description_en',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='fourthblock_description_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='fourthblock_description_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='fourthblock_img',
            field=models.ImageField(default=1, upload_to='indexpage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='fourthblock_title_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='fourthblock_title_ru',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='fourthblock_title_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
