# Generated by Django 4.0.4 on 2022-09-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_indexpagemodel_fourthblock_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageFAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ru', models.CharField(max_length=200)),
                ('question_en', models.CharField(max_length=200)),
                ('question_uz', models.CharField(max_length=200)),
                ('answer_ru', models.TextField()),
                ('answer_en', models.TextField()),
                ('answer_uz', models.TextField()),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
            },
        ),
    ]
