# Generated by Django 4.0.4 on 2022-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_reviewmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='position',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='text',
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='name_en',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='name_ru',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='name_uz',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='position_en',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='position_ru',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='position_uz',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='text_en',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='text_ru',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='text_uz',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
