# Generated by Django 4.0.4 on 2022-09-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_indexpagemodel_eighthblock_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField()),
                ('img', models.ImageField(upload_to='news/')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
