# Generated by Django 4.0.4 on 2022-09-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_indexpagemodel_copyright'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexpagemodel',
            old_name='copyright',
            new_name='copyright_ru',
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='copyright_en',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpagemodel',
            name='copyright_uz',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
