# Generated by Django 4.0.4 on 2022-09-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_rename_copyright_indexpagemodel_copyright_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='header/')),
            ],
            options={
                'verbose_name': 'Шапка сайта',
                'verbose_name_plural': 'Шапка сайта',
            },
        ),
    ]
