# Generated by Django 4.0.4 on 2022-09-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_header'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header',
            new_name='HeaderModel',
        ),
    ]
