# Generated by Django 4.0.4 on 2022-09-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_rename_header_headermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='footer/')),
                ('description_ru', models.TextField()),
                ('description_en', models.TextField()),
                ('description_uz', models.TextField()),
                ('address_ru', models.CharField(max_length=200)),
                ('address_en', models.CharField(max_length=200)),
                ('address_uz', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('mail_description', models.TextField()),
                ('facebook', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('telegram', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
            ],
        ),
    ]
