# Generated by Django 4.0.4 on 2022-09-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_footermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footermodel',
            options={'verbose_name': 'Подвал сайта', 'verbose_name_plural': 'Подвал сайта'},
        ),
        migrations.RenameField(
            model_name='footermodel',
            old_name='mail_description',
            new_name='mail_description_en',
        ),
        migrations.AddField(
            model_name='footermodel',
            name='mail_description_ru',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footermodel',
            name='mail_description_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
