# Generated by Django 4.0.4 on 2022-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_alter_footermodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписка',
            },
        ),
    ]
