# Generated by Django 4.0.4 on 2022-09-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_newslistpagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslistpagemodel',
            name='description_en',
            field=models.TextField(verbose_name='Описание на английском'),
        ),
        migrations.AlterField(
            model_name='newslistpagemodel',
            name='description_uz',
            field=models.TextField(verbose_name='Описание на узбекском'),
        ),
    ]
