# Generated by Django 4.0.4 on 2022-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_alter_newslistpagemodel_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='text_en',
            field=models.TextField(default=1, verbose_name='Текст на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='text_ru',
            field=models.TextField(default=1, verbose_name='Текст на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='text_uz',
            field=models.TextField(default=1, verbose_name='Текст на узбекском'),
            preserve_default=False,
        ),
    ]
