# Generated by Django 4.0.4 on 2022-09-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='new',
            field=models.BooleanField(default=1, verbose_name='Новинка'),
            preserve_default=False,
        ),
    ]
