# Generated by Django 4.0.4 on 2022-10-21 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_subcategorymodel_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='category',
            new_name='subcategory',
        ),
    ]
