# Generated by Django 4.0.4 on 2022-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_rename_category_productmodel_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='img',
            field=models.ImageField(default=1, upload_to='subcategories/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
