# Generated by Django 4.0.4 on 2022-11-18 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_subcategorymodel_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategorymodel',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='mainapp.subcategorymodel', verbose_name='Коллекция'),
        ),
    ]
