# Generated by Django 4.0.4 on 2023-01-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_alter_subcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategoryModel',
            new_name='CollectionModel',
        ),
    ]
