# Generated by Django 4.0.4 on 2023-01-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_rename_subcategorymodel_collectionmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='subcategory',
            new_name='collection',
        ),
    ]
