# Generated by Django 4.0.4 on 2023-01-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_rename_subcategory_productmodel_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='img',
            field=models.ImageField(upload_to='collections/', verbose_name='Изображение'),
        ),
    ]
