# Generated by Django 4.0.4 on 2023-01-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_alter_collectionmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='mainapp.categorymodel', verbose_name='Категория'),
        ),
    ]
