# Generated by Django 4.0.4 on 2023-01-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0057_alter_collectionmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='show_price',
            field=models.BooleanField(default=1, verbose_name='Показывать цену'),
            preserve_default=False,
        ),
    ]
