# Generated by Django 4.0.4 on 2023-01-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0059_subcategorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='has_subcategory',
            field=models.BooleanField(default=1, verbose_name='Есть подкатегории'),
            preserve_default=False,
        ),
    ]
