# Generated by Django 4.0.4 on 2023-01-31 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0060_categorymodel_has_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmodel',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='mainapp.subcategorymodel', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='mainapp.categorymodel', verbose_name='Категория'),
        ),
    ]
